export const chordQualities = {
  major: [0, 4, 7],
  minor: [0, 3, 7],
  M7: [0, 4, 7, 11],
  m7: [0, 3, 7, 10],
  "7": [0, 4, 7, 10],
  m7b5: [0, 3, 6, 10],
  dim: [0, 3, 6],
  dim7: [0, 3, 6, 9],
  aug: [0, 4, 8],
  sus4: [0, 5, 7],
  "7sus4": [0, 5, 7, 10],
  "6": [0, 4, 7, 9],
  m6: [0, 3, 7, 9],
  mM7: [0, 3, 7, 11],
  add9: [0, 4, 7, 14]
};

// パース時に長い文字列から順にマッチさせるためのリスト
export const qualityAliases = [
  { match: "m7b5", quality: "m7b5" },
  { match: "m7-5", quality: "m7b5" },
  { match: "ø7", quality: "m7b5" },
  { match: "7sus4", quality: "7sus4" },
  { match: "7sus", quality: "7sus4" },
  { match: "mMaj7", quality: "mM7" },
  { match: "mM7", quality: "mM7" },
  { match: "dim7", quality: "dim7" },
  { match: "add9", quality: "add9" },
  { match: "maj7", quality: "M7" },
  { match: "min7", quality: "m7" },
  { match: "sus4", quality: "sus4" },
  { match: "sus", quality: "sus4" },
  { match: "dim", quality: "dim" },
  { match: "aug", quality: "aug" },
  { match: "M7", quality: "M7" },
  { match: "△7", quality: "M7" },
  { match: "m7", quality: "m7" },
  { match: "m6", quality: "m6" },
  { match: "o7", quality: "dim7" },
  { match: "min", quality: "minor" },
  { match: "maj", quality: "major" },
  { match: "7", quality: "7" },
  { match: "6", quality: "6" },
  { match: "m", quality: "minor" },
  { match: "M", quality: "major" },
  { match: "+", quality: "aug" },
  { match: "", quality: "major" }
];
